### ISSUE TITLE
Add a dash to the name

### ISSUE THREAD

**Issue by nfriedly** [bevry-archive/goopen#9]
My first thought upon seeing the github link was "What the heck is a Goo Pen?"

:P

(Only partially serious. You can keep the name if you want, it won't offend me.)

**Comment by balupton** [comment]
Hehehe. Yeah, I guess that is totally a possibility! Haha.

I use to use dashes in names for things, but then it always raises the questions, where does the dash go, does this project have a dash, do you do a dash between hyphenated words, etc. In the end, I decided no dashes every in project names works out best.
